### ISSUE TITLE
Error loading mod Epic Psi: WeaponItem class not found

### ISSUE THREAD

**Issue by Duskhorn** [TehFlaminTaco/EpicPsi#1]
The forge launcher throws an error on mod loading, it seems unable to find the WeaponItem class

Epic Psi version: 1.0
Psi version: 1.16-91
minecraft version: 1.16.5

[here's the full crash report](https://pastebin.com/se6VsDHj)

screenshot of the error:
![Screenshot 2021-03-16 104725](https://user-images.githubusercontent.com/77054257/111289042-0a621e80-8645-11eb-9b7b-f409e0f65cb8.jpg)

**Comment by TehFlaminTaco** [comment]
Hi,

Have you got the [Epic Fight Mod](https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod/files) installed?

I may need to fix the mod's dependency settings if it's not throwing the correct error if it's not present.

**Comment by Duskhorn** [comment]
I have not installed that, I'll try with the mod tomorrow!
My fault for not checking all the dependencies first 😊
