### ISSUE TITLE
NoClassDefFoundError when run on a Mohist Forge Server

### ISSUE THREAD

**Issue by archonxgames** [TehFlaminTaco/EpicPsi#2]
Forge Version: 36.1.0
Minecraft Version: 1.16.5
Psi Version: 1.16-91
Epic Fight Version: 3.0.4

Works fine in singleplayer, but when I try to add it to my modded server, it crashes on startup.

Error: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/tileentity/ItemStackTileEntityRenderer

Full crash report below:
[crash-2021-03-17_20.18.45-fml.txt](https://github.com/TehFlaminTaco/EpicPsi/files/6159524/crash-2021-03-17_20.18.45-fml.txt)

**Comment by TehFlaminTaco** [comment]
Ah, I failed to account for multiplayer. This should be relatively easy to tackle.

**Comment by TehFlaminTaco** [comment]
Thanks for the heads up about this, it should work fine for all your server needs now! :D

**Comment by archonxgames** [comment]
Great, can't wait to use this for multiplayer! Cheers.

**Comment by archonxgames** [comment]
A different issue has popped up, Epic Psi causes a server-side crash when joining a world or server. 

Server crash report: [crash-2021-03-19_07.23.38-server.txt](https://github.com/TehFlaminTaco/EpicPsi/files/6169408/crash-2021-03-19_07.23.38-server.txt)

Singleplayer crash report: [crash-2021-03-19_15.36.49-server.txt](https://github.com/TehFlaminTaco/EpicPsi/files/6169409/crash-2021-03-19_15.36.49-server.txt)
