### ISSUE TITLE
Epic Psi causes a server-side crash when joining a world or server.

### ISSUE THREAD

**Issue by archonxgames** [TehFlaminTaco/EpicPsi#3]
With Epic Psi installed, joining a server or singleplayer world would cause it to crash on the server-side.

Server crash report: [crash-2021-03-19_07.23.38-server.txt](https://github.com/TehFlaminTaco/EpicPsi/files/6169408/crash-2021-03-19_07.23.38-server.txt)

Singleplayer crash report: [crash-2021-03-19_15.36.49-server.txt](https://github.com/TehFlaminTaco/EpicPsi/files/6169409/crash-2021-03-19_15.36.49-server.txt)

_Originally posted by @archonxgames in https://github.com/TehFlaminTaco/EpicPsi/issues/2#issuecomment-802624101_

**Comment by TehFlaminTaco** [comment]
Hi, can you confirm if this still occurs when Epic Psi is removed, but Epic Fight remains installed?

**Comment by archonxgames** [comment]
Can confirm, though it seems to only prevail in an existing world than a newly created one.

**Comment by archonxgames** [comment]
I suspect it to be a weird interaction between Epic Fights mod and any child mod it has, am looking more into it.

**Comment by archonxgames** [comment]
It is an issue with Epic Fight mod, apologies for the misinformation.
