### ISSUE TITLE
No Method Error?

### ISSUE THREAD

**Issue by mathematiqueNageur** [TehFlaminTaco/EpicPsi#4]
Forge Version: forge-36.1.3
Mods: 

- Psi 1.16-92
- Patchouli-1.16.4-50
- epicpsi-1.1
- EpicFightMod-1.16.5-3.1.1

Log:
[https://pastebin.com/bVRAAQn7](https://pastebin.com/bVRAAQn7)

Error thrown while loading Minecraft.

**Comment by TehFlaminTaco** [comment]
This is due to an update to Epic Fight that restructures some things, I need to update Epic Psi to match.
