### ISSUE TITLE
 		java.lang.AbstractMethodError: maninhouse.epicfight.item.WeaponItem.setWeaponCapability(Lnet/minecraft/item/IItemTier;)V

### ISSUE THREAD

**Issue by Tyfyter** [TehFlaminTaco/EpicPsi#5]
This should be able to be fixed by adding an IItemTier parameter to each setWeaponCapability override, ~~but these items should probably just extend the relevant epicfight classes (SpearItem, GreatswordItem, etc.) instead of WeaponItem~~

**Comment by TehFlaminTaco** [comment]
In previous versions, (Though I haven't checked the most recent build), SpearItem and GreatswordItem didn't accept the correct ItemTier class, which meant I had to skip them. Updating to the latest version of Epic Fight shouldn't be too hard.
